export interface TickerData {
  Name: string;
  Sector: string;
  Symbol: string;
  Contact?: string;
  Email?: string;
}

export const rowData: TickerData[] = [
  {
    Name: '3M Company',
    Sector: 'Industrials',
    Symbol: 'MMM',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  {
    Name: 'A.O. Smith Corp',
    Sector: 'Industrials',
    Symbol: 'AOS',
    Contact: "Seb Ben M'Barek",
    Email: 'sebastien.benmbarek@normanandsons.com',
  },
  {
    Name: 'Abbott Laboratories',
    Sector: 'Health Care',
    Symbol: 'ABT',
    Contact: 'Rob Moffat',
    Email: 'rob.moffat@hsbc.com',
  },
  {
    Name: 'AbbVie Inc.',
    Sector: 'Health Care',
    Symbol: 'ABBV',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  {
    Name: 'Abiomed',
    Sector: 'Health Care',
    Symbol: 'ABMD',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  {
    Name: 'Accenture plc',
    Sector: 'Technology',
    Symbol: 'ACN',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  {
    Name: 'Activision Blizzard',
    Sector: 'Technology',
    Symbol: 'ATVI',
    Contact: 'Rob Moffat',
    Email: 'rob.moffat@hsbc.com',
  },
  {
    Name: 'ADM',
    Sector: 'Consumer',
    Symbol: 'ADM',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  {
    Name: 'Adobe Systems Inc',
    Sector: 'Technology',
    Symbol: 'ADBE',
    Contact: "Seb Ben M'Barek",
    Email: 'sebastien.benmbarek@normanandsons.com',
  },
  {
    Name: 'Advance Auto Parts',
    Sector: 'Consumer',
    Symbol: 'AAP',
    Contact: "Seb Ben M'Barek",
    Email: 'sebastien.benmbarek@normanandsons.com',
  },
  {
    Name: 'Advanced Micro Devices Inc',
    Sector: 'Technology',
    Symbol: 'AMD',
    Contact: 'Rob Moffat',
    Email: 'rob.moffat@hsbc.com',
  },
  {
    Name: 'AES Corp',
    Sector: 'Utilities',
    Symbol: 'AES',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  { Name: 'Aetna Inc', Sector: 'Health Care', Symbol: 'AET' },
  {
    Name: 'Affiliated Managers Group Inc',
    Sector: 'Financials',
    Symbol: 'AMG',
  },
  {
    Name: 'AFLAC Inc',
    Sector: 'Financials',
    Symbol: 'AFL',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  { Name: 'Agilent Technologies Inc', Sector: 'Health Care', Symbol: 'A' },
  {
    Name: 'Air Products & Chemicals Inc',
    Sector: 'Industrials',
    Symbol: 'APD',
    Contact: "Seb Ben M'Barek",
    Email: 'sebastien.benmbarek@normanandsons.com',
  },
  {
    Name: 'Akamai Technologies Inc',
    Sector: 'Technology',
    Symbol: 'AKAM',
    Contact: 'Rob Moffat',
    Email: 'rob.moffat@hsbc.com',
  },
  {
    Name: 'Alaska Air Group Inc',
    Sector: 'Industrials',
    Symbol: 'ALK',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  { Name: 'Albemarle Corp', Sector: 'Industrials', Symbol: 'ALB' },
  {
    Name: 'Alexandria Real Estate Equities Inc',
    Sector: 'Real Estate',
    Symbol: 'ARE',
    Contact: 'Rob Moffat',
    Email: 'rob.moffat@hsbc.com',
  },
  {
    Name: 'Alexion Pharmaceuticals',
    Sector: 'Health Care',
    Symbol: 'ALXN',
    Contact: "Seb Ben M'Barek",
    Email: 'sebastien.benmbarek@normanandsons.com',
  },
  {
    Name: 'Align Technology',
    Sector: 'Health Care',
    Symbol: 'ALGN',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  {
    Name: 'Allegion',
    Sector: 'Industrials',
    Symbol: 'ALLE',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  {
    Name: 'Allergan, Plc',
    Sector: 'Health Care',
    Symbol: 'AGN',
    Contact: 'Rob Moffat',
    Email: 'rob.moffat@hsbc.com',
  },
  {
    Name: 'Alliance Data Systems',
    Sector: 'Technology',
    Symbol: 'ADS',
  },
  {
    Name: 'Alliant Energy Corp',
    Sector: 'Utilities',
    Symbol: 'LNT',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  {
    Name: 'Allstate Corp',
    Sector: 'Financials',
    Symbol: 'ALL',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  {
    Name: 'Alphabet Inc Class A',
    Sector: 'Technology',
    Symbol: 'GOOGL',
    Contact: 'Rob Moffat',
    Email: 'rob.moffat@hsbc.com',
  },
  {
    Name: 'Alphabet Inc Class C',
    Sector: 'Technology',
    Symbol: 'GOOG',
  },
  { Name: 'Altria Group Inc', Sector: 'Consumer', Symbol: 'MO' },
  {
    Name: 'Amazon.com Inc.',
    Sector: 'Consumer',
    Symbol: 'AMZN',
    Contact: "Seb Ben M'Barek",
    Email: 'sebastien.benmbarek@normanandsons.com',
  },
  { Name: 'Ameren Corp', Sector: 'Utilities', Symbol: 'AEE' },
  {
    Name: 'American Airlines Group',
    Sector: 'Industrials',
    Symbol: 'AAL',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  {
    Name: 'American Electric Power',
    Sector: 'Utilities',
    Symbol: 'AEP',
    Contact: "Seb Ben M'Barek",
    Email: 'sebastien.benmbarek@normanandsons.com',
  },
  {
    Name: 'American Express Co',
    Sector: 'Financials',
    Symbol: 'AXP',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  {
    Name: 'American International Group, Inc.',
    Sector: 'Financials',
    Symbol: 'AIG',
    Contact: 'Rob Moffat',
    Email: 'rob.moffat@hsbc.com',
  },
  {
    Name: 'American Tower Corp A',
    Sector: 'Real Estate',
    Symbol: 'AMT',
    Contact: "Seb Ben M'Barek",
    Email: 'sebastien.benmbarek@normanandsons.com',
  },
  {
    Name: 'American Water Works Company Inc',
    Sector: 'Utilities',
    Symbol: 'AWK',
  },
  {
    Name: 'Ameriprise Financial',
    Sector: 'Financials',
    Symbol: 'AMP',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  { Name: 'AmerisourceBergen Corp', Sector: 'Health Care', Symbol: 'ABC' },
  { Name: 'AMETEK Inc.', Sector: 'Industrials', Symbol: 'AME' },
  { Name: 'Amgen Inc.', Sector: 'Health Care', Symbol: 'AMGN' },
  {
    Name: 'Amphenol Corp',
    Sector: 'Technology',
    Symbol: 'APH',
    Contact: "Seb Ben M'Barek",
    Email: 'sebastien.benmbarek@normanandsons.com',
  },
  { Name: 'Anadarko Petroleum Corp', Sector: 'Energy', Symbol: 'APC' },
  {
    Name: 'Analog Devices, Inc.',
    Sector: 'Technology',
    Symbol: 'ADI',
    Contact: "Seb Ben M'Barek",
    Email: 'sebastien.benmbarek@normanandsons.com',
  },
  { Name: 'Andeavor', Sector: 'Energy', Symbol: 'ANDV' },
  {
    Name: 'ANSYS',
    Sector: 'Technology',
    Symbol: 'ANSS',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  { Name: 'Anthem Inc.', Sector: 'Health Care', Symbol: 'ANTM' },
  { Name: 'Aon plc', Sector: 'Financials', Symbol: 'AON' },
  { Name: 'Apache Corporation', Sector: 'Energy', Symbol: 'APA' },
  {
    Name: 'Apartment Investment & Management',
    Sector: 'Real Estate',
    Symbol: 'AIV',
  },
  { Name: 'Apple Inc.', Sector: 'Technology', Symbol: 'AAPL' },
  {
    Name: 'Applied Industrials Inc.',
    Sector: 'Technology',
    Symbol: 'AMAT',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  { Name: 'Aptiv Plc', Sector: 'Consumer', Symbol: 'APTV' },
  {
    Name: 'Archer-Daniels-Midland Co',
    Sector: 'Consumer',
    Symbol: 'ADM',
    Contact: "Seb Ben M'Barek",
    Email: 'sebastien.benmbarek@normanandsons.com',
  },
  { Name: 'Arconic Inc.', Sector: 'Industrials', Symbol: 'ARNC' },
  {
    Name: 'Arthur J. Gallagher & Co.',
    Sector: 'Financials',
    Symbol: 'AJG',
    Contact: "Seb Ben M'Barek",
    Email: 'sebastien.benmbarek@normanandsons.com',
  },
  { Name: 'Assurant Inc.', Sector: 'Financials', Symbol: 'AIZ' },
  {
    Name: 'AT&T Inc.',
    Sector: 'Technology',
    Symbol: 'T',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  {
    Name: 'Autodesk Inc.',
    Sector: 'Technology',
    Symbol: 'ADSK',
    Contact: "Seb Ben M'Barek",
    Email: 'sebastien.benmbarek@normanandsons.com',
  },
  {
    Name: 'Automatic Data Processing',
    Sector: 'Technology',
    Symbol: 'ADP',
    Contact: 'Rob Moffat',
    Email: 'rob.moffat@hsbc.com',
  },
  { Name: 'AutoZone Inc', Sector: 'Consumer', Symbol: 'AZO' },
  { Name: 'AvalonBay Communities, Inc.', Sector: 'Real Estate', Symbol: 'AVB' },
  {
    Name: 'Avery Dennison Corp',
    Sector: 'Industrials',
    Symbol: 'AVY',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  {
    Name: 'Baker Hughes, a GE Company',
    Sector: 'Energy',
    Symbol: 'BHGE',
    Contact: "Seb Ben M'Barek",
    Email: 'sebastien.benmbarek@normanandsons.com',
  },
  { Name: 'Ball Corp', Sector: 'Industrials', Symbol: 'BLL' },
  { Name: 'Bank of America Corp', Sector: 'Financials', Symbol: 'BAC' },
  {
    Name: 'Baxter International Inc.',
    Sector: 'Health Care',
    Symbol: 'BAX',
    Contact: 'Rob Moffat',
    Email: 'rob.moffat@hsbc.com',
  },
  { Name: 'BB&T Corporation', Sector: 'Financials', Symbol: 'BBT' },
  {
    Name: 'Becton Dickinson',
    Sector: 'Health Care',
    Symbol: 'BDX',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  { Name: 'Berkshire Hathaway', Sector: 'Financials', Symbol: 'BRK.B' },
  {
    Name: 'Best Buy Co. Inc.',
    Sector: 'Consumer',
    Symbol: 'BBY',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  { Name: 'Biogen Inc.', Sector: 'Health Care', Symbol: 'BIIB' },
  {
    Name: 'BlackRock',
    Sector: 'Financials',
    Symbol: 'BLK',
    Contact: 'Rob Moffat',
    Email: 'rob.moffat@hsbc.com',
  },
  {
    Name: 'Block H&R',
    Sector: 'Financials',
    Symbol: 'HRB',
    Contact: 'Rob Moffat',
    Email: 'rob.moffat@hsbc.com',
  },
  { Name: 'Boeing Company', Sector: 'Industrials', Symbol: 'BA' },
  {
    Name: 'Booking Holdings Inc',
    Sector: 'Consumer',
    Symbol: 'BKNG',
    Contact: 'Rob Moffat',
    Email: 'rob.moffat@hsbc.com',
  },
  {
    Name: 'BorgWarner',
    Sector: 'Consumer',
    Symbol: 'BWA',
    Contact: "Seb Ben M'Barek",
    Email: 'sebastien.benmbarek@normanandsons.com',
  },
  {
    Name: 'Boston Properties',
    Sector: 'Real Estate',
    Symbol: 'BXP',
    Contact: "Seb Ben M'Barek",
    Email: 'sebastien.benmbarek@normanandsons.com',
  },
  { Name: 'Boston Scientific', Sector: 'Health Care', Symbol: 'BSX' },
  { Name: 'Brighthouse Financial Inc', Sector: 'Financials', Symbol: 'BHF' },
  { Name: 'Bristol-Myers Squibb', Sector: 'Health Care', Symbol: 'BMY' },
  { Name: 'Broadcom', Sector: 'Technology', Symbol: 'AVGO' },
  { Name: 'Brown-Forman Corp.', Sector: 'Consumer', Symbol: 'BF.B' },
  {
    Name: 'C. H. Robinson Worldwide',
    Sector: 'Industrials',
    Symbol: 'CHRW',
    Contact: "Seb Ben M'Barek",
    Email: 'sebastien.benmbarek@normanandsons.com',
  },
  {
    Name: 'CA, Inc.',
    Sector: 'Technology',
    Symbol: 'CA',
    Contact: 'Nick Kolba',
    Email: 'nkolba@gmail.com',
  },
  { Name: 'Cabot Oil & Gas', Sector: 'Energy', Symbol: 'COG' },
  {
    Name: 'Cadence Design Systems',
    Sector: 'Technology',
    Symbol: 'CDNS',
  },
  { Name: 'Campbell Soup', Sector: 'Consumer', Symbol: 'CPB' },
  { Name: 'Capital One Financial', Sector: 'Financials', Symbol: 'COF' },
  { Name: 'Cardinal Health Inc.', Sector: 'Health Care', Symbol: 'CAH' },
  { Name: 'Carmax Inc', Sector: 'Consumer', Symbol: 'KMX' },
  { Name: 'Carnival Corp.', Sector: 'Consumer', Symbol: 'CCL' },
  { Name: 'Caterpillar Inc.', Sector: 'Industrials', Symbol: 'CAT' },
  { Name: 'Cboe Global Markets', Sector: 'Financials', Symbol: 'CBOE' },
  { Name: 'CBRE Group', Sector: 'Real Estate', Symbol: 'CBRE' },
  { Name: 'CBS Corp.', Sector: 'Consumer', Symbol: 'CBS' },
  { Name: 'Celgene Corp.', Sector: 'Health Care', Symbol: 'CELG' },
  { Name: 'Centene Corporation', Sector: 'Health Care', Symbol: 'CNC' },
  { Name: 'CenterPoint Energy', Sector: 'Utilities', Symbol: 'CNP' },
  {
    Name: 'CenturyLink Inc',
    Sector: 'Technology',
    Symbol: 'CTL',
  },
  { Name: 'Cerner', Sector: 'Health Care', Symbol: 'CERN' },
  { Name: 'CF Industries Holdings Inc', Sector: 'Industrials', Symbol: 'CF' },
  { Name: 'Charles Schwab Corporation', Sector: 'Financials', Symbol: 'SCHW' },
  {
    Name: 'Charter Communications',
    Sector: 'Consumer',
    Symbol: 'CHTR',
  },
  { Name: 'Chevron Corp.', Sector: 'Energy', Symbol: 'CVX' },
  {
    Name: 'Chipotle Mexican Grill',
    Sector: 'Consumer',
    Symbol: 'CMG',
  },
  { Name: 'Chubb Limited', Sector: 'Financials', Symbol: 'CB' },
  { Name: 'Church & Dwight', Sector: 'Consumer', Symbol: 'CHD' },
  { Name: 'CIGNA Corp.', Sector: 'Health Care', Symbol: 'CI' },
  { Name: 'Cimarex Energy', Sector: 'Energy', Symbol: 'XEC' },
  { Name: 'Cincinnati Financial', Sector: 'Financials', Symbol: 'CINF' },
  { Name: 'Cintas Corporation', Sector: 'Industrials', Symbol: 'CTAS' },
  { Name: 'Cisco Systems', Sector: 'Technology', Symbol: 'CSCO' },
  { Name: 'Citigroup Inc.', Sector: 'Financials', Symbol: 'C' },
  { Name: 'Citizens Financial Group', Sector: 'Financials', Symbol: 'CFG' },
  { Name: 'Citrix Systems', Sector: 'Technology', Symbol: 'CTXS' },
  { Name: 'CME Group Inc.', Sector: 'Financials', Symbol: 'CME' },
  { Name: 'CMS Energy', Sector: 'Utilities', Symbol: 'CMS' },
  { Name: 'Coca-Cola Company (The)', Sector: 'Consumer', Symbol: 'KO' },
  {
    Name: 'Cognizant Technology Solutions',
    Sector: 'Technology',
    Symbol: 'CTSH',
  },
  { Name: 'Colgate-Palmolive', Sector: 'Consumer', Symbol: 'CL' },
  { Name: 'Comcast Corp.', Sector: 'Consumer', Symbol: 'CMCSA' },
  { Name: 'Comerica Inc.', Sector: 'Financials', Symbol: 'CMA' },
  { Name: 'Conagra Brands', Sector: 'Consumer', Symbol: 'CAG' },
  { Name: 'Concho Resources', Sector: 'Energy', Symbol: 'CXO' },
  { Name: 'ConocoPhillips', Sector: 'Energy', Symbol: 'COP' },
  { Name: 'Consolidated Edison', Sector: 'Utilities', Symbol: 'ED' },
  { Name: 'Constellation Brands', Sector: 'Consumer', Symbol: 'STZ' },
  { Name: 'Corning Inc.', Sector: 'Technology', Symbol: 'GLW' },
  {
    Name: 'Costco Wholesale Corp.',
    Sector: 'Consumer',
    Symbol: 'COST',
  },
  { Name: 'Coty, Inc', Sector: 'Consumer', Symbol: 'COTY' },
  {
    Name: 'Crown Castle International Corp.',
    Sector: 'Real Estate',
    Symbol: 'CCI',
  },
  { Name: 'CSRA Inc.', Sector: 'Technology', Symbol: 'CSRA' },
  { Name: 'CSX Corp.', Sector: 'Industrials', Symbol: 'CSX' },
  { Name: 'Cummins Inc.', Sector: 'Industrials', Symbol: 'CMI' },
  { Name: 'CVS Health', Sector: 'Consumer', Symbol: 'CVS' },
  { Name: 'D. R. Horton', Sector: 'Consumer', Symbol: 'DHI' },
  { Name: 'Danaher Corp.', Sector: 'Health Care', Symbol: 'DHR' },
  {
    Name: 'Darden Restaurants',
    Sector: 'Consumer',
    Symbol: 'DRI',
  },
  { Name: 'DaVita Inc.', Sector: 'Health Care', Symbol: 'DVA' },
  { Name: 'Deere & Co.', Sector: 'Industrials', Symbol: 'DE' },
  { Name: 'Delta Air Lines Inc.', Sector: 'Industrials', Symbol: 'DAL' },
  { Name: 'Dentsply Sirona', Sector: 'Health Care', Symbol: 'XRAY' },
  { Name: 'Devon Energy Corp.', Sector: 'Energy', Symbol: 'DVN' },
  { Name: 'Digital Realty Trust Inc', Sector: 'Real Estate', Symbol: 'DLR' },
  { Name: 'Discover Financial Services', Sector: 'Financials', Symbol: 'DFS' },
  {
    Name: 'Discovery Inc. Class A',
    Sector: 'Consumer',
    Symbol: 'DISCA',
  },
  {
    Name: 'Discovery Inc. Class C',
    Sector: 'Consumer',
    Symbol: 'DISCK',
  },
  { Name: 'Dish Network', Sector: 'Consumer', Symbol: 'DISH' },
  { Name: 'Dollar General', Sector: 'Consumer', Symbol: 'DG' },
  { Name: 'Dollar Tree', Sector: 'Consumer', Symbol: 'DLTR' },
  { Name: 'Dominion Energy', Sector: 'Utilities', Symbol: 'D' },
  { Name: 'Dover Corp.', Sector: 'Industrials', Symbol: 'DOV' },
  { Name: 'DowDuPont', Sector: 'Industrials', Symbol: 'DWDP' },
  {
    Name: 'Dr Pepper Snapple Group',
    Sector: 'Consumer',
    Symbol: 'DPS',
  },
  { Name: 'DTE Energy Co.', Sector: 'Utilities', Symbol: 'DTE' },
  { Name: 'Duke Energy', Sector: 'Utilities', Symbol: 'DUK' },
  { Name: 'Duke Realty Corp', Sector: 'Real Estate', Symbol: 'DRE' },
  { Name: 'DXC Technology', Sector: 'Technology', Symbol: 'DXC' },
  { Name: 'E*Trade', Sector: 'Financials', Symbol: 'ETFC' },
  { Name: 'Eastman Chemical', Sector: 'Industrials', Symbol: 'EMN' },
  { Name: 'Eaton Corporation', Sector: 'Industrials', Symbol: 'ETN' },
  { Name: 'eBay Inc.', Sector: 'Technology', Symbol: 'EBAY' },
  { Name: 'Ecolab Inc.', Sector: 'Industrials', Symbol: 'ECL' },
  { Name: "Edison Int'l", Sector: 'Utilities', Symbol: 'EIX' },
  { Name: 'Edwards Lifesciences', Sector: 'Health Care', Symbol: 'EW' },
  { Name: 'Electronic Arts', Sector: 'Technology', Symbol: 'EA' },
  { Name: 'Emerson Electric Company', Sector: 'Industrials', Symbol: 'EMR' },
  { Name: 'Entergy Corp.', Sector: 'Utilities', Symbol: 'ETR' },
  { Name: 'Envision Healthcare', Sector: 'Health Care', Symbol: 'EVHC' },
  { Name: 'EOG Resources', Sector: 'Energy', Symbol: 'EOG' },
  { Name: 'EQT Corporation', Sector: 'Energy', Symbol: 'EQT' },
  { Name: 'Equifax Inc.', Sector: 'Industrials', Symbol: 'EFX' },
  { Name: 'Equinix', Sector: 'Real Estate', Symbol: 'EQIX' },
  { Name: 'Equity Residential', Sector: 'Real Estate', Symbol: 'EQR' },
  { Name: 'Essex Property Trust, Inc.', Sector: 'Real Estate', Symbol: 'ESS' },
  { Name: 'Estee Lauder Cos.', Sector: 'Consumer', Symbol: 'EL' },
  { Name: 'Everest Re Group Ltd.', Sector: 'Financials', Symbol: 'RE' },
  { Name: 'Eversource Energy', Sector: 'Utilities', Symbol: 'ES' },
  { Name: 'Exelon Corp.', Sector: 'Utilities', Symbol: 'EXC' },
  { Name: 'Expedia Inc.', Sector: 'Consumer', Symbol: 'EXPE' },
  { Name: 'Expeditors International', Sector: 'Industrials', Symbol: 'EXPD' },
  { Name: 'Express Scripts', Sector: 'Health Care', Symbol: 'ESRX' },
  { Name: 'Extra Space Storage', Sector: 'Real Estate', Symbol: 'EXR' },
  { Name: 'Exxon Mobil Corp.', Sector: 'Energy', Symbol: 'XOM' },
  { Name: 'F5 Networks', Sector: 'Technology', Symbol: 'FFIV' },
  { Name: 'Fastenal Co', Sector: 'Industrials', Symbol: 'FAST' },
  {
    Name: 'Federal Realty Investment Trust',
    Sector: 'Real Estate',
    Symbol: 'FRT',
  },
  { Name: 'FedEx Corporation', Sector: 'Industrials', Symbol: 'FDX' },
  {
    Name: 'Fidelity National Information Services',
    Sector: 'Technology',
    Symbol: 'FIS',
  },
  { Name: 'Fifth Third Bancorp', Sector: 'Financials', Symbol: 'FITB' },
  { Name: 'FirstEnergy Corp', Sector: 'Utilities', Symbol: 'FE' },
  { Name: 'Fiserv Inc', Sector: 'Technology', Symbol: 'FISV' },
  { Name: 'FLIR Systems', Sector: 'Technology', Symbol: 'FLIR' },
  { Name: 'Flowserve Corporation', Sector: 'Industrials', Symbol: 'FLS' },
  { Name: 'Fluor Corp.', Sector: 'Industrials', Symbol: 'FLR' },
  { Name: 'FMC Corporation', Sector: 'Industrials', Symbol: 'FMC' },
  { Name: 'Foot Locker Inc', Sector: 'Consumer', Symbol: 'FL' },
  { Name: 'Ford Motor', Sector: 'Consumer', Symbol: 'F' },
  { Name: 'Fortive Corp', Sector: 'Industrials', Symbol: 'FTV' },
  {
    Name: 'Fortune Brands Home & Security',
    Sector: 'Industrials',
    Symbol: 'FBHS',
  },
  { Name: 'Franklin Resources', Sector: 'Financials', Symbol: 'BEN' },
  { Name: 'Freeport-McMoRan Inc.', Sector: 'Industrials', Symbol: 'FCX' },
  { Name: 'Gap Inc.', Sector: 'Consumer', Symbol: 'GPS' },
  { Name: 'Garmin Ltd.', Sector: 'Consumer', Symbol: 'GRMN' },
  { Name: 'Gartner Inc', Sector: 'Technology', Symbol: 'IT' },
  { Name: 'General Dynamics', Sector: 'Industrials', Symbol: 'GD' },
  { Name: 'General Electric', Sector: 'Industrials', Symbol: 'GE' },
  {
    Name: 'General Growth Properties Inc.',
    Sector: 'Real Estate',
    Symbol: 'GGP',
  },
  { Name: 'General Mills', Sector: 'Consumer', Symbol: 'GIS' },
  { Name: 'General Motors', Sector: 'Consumer', Symbol: 'GM' },
  { Name: 'Genuine Parts', Sector: 'Consumer', Symbol: 'GPC' },
  { Name: 'Gilead Sciences', Sector: 'Health Care', Symbol: 'GILD' },
  {
    Name: 'Global Payments Inc.',
    Sector: 'Technology',
    Symbol: 'GPN',
  },
  { Name: 'Goldman Sachs Group', Sector: 'Financials', Symbol: 'GS' },
  {
    Name: 'Goodyear Tire & Rubber',
    Sector: 'Consumer',
    Symbol: 'GT',
  },
  { Name: 'Grainger (W.W.) Inc.', Sector: 'Industrials', Symbol: 'GWW' },
  { Name: 'Halliburton Co.', Sector: 'Energy', Symbol: 'HAL' },
  { Name: 'Hanesbrands Inc', Sector: 'Consumer', Symbol: 'HBI' },
  { Name: 'Harley-Davidson', Sector: 'Consumer', Symbol: 'HOG' },
  {
    Name: 'Harris Corporation',
    Sector: 'Technology',
    Symbol: 'HRS',
  },
  { Name: 'Hartford Financial Svc.Gp.', Sector: 'Financials', Symbol: 'HIG' },
  { Name: 'Hasbro Inc.', Sector: 'Consumer', Symbol: 'HAS' },
  { Name: 'HCA Holdings', Sector: 'Health Care', Symbol: 'HCA' },
  { Name: 'HCP Inc.', Sector: 'Real Estate', Symbol: 'HCP' },
  { Name: 'Helmerich & Payne', Sector: 'Energy', Symbol: 'HP' },
  { Name: 'Henry Schein', Sector: 'Health Care', Symbol: 'HSIC' },
  { Name: 'Hess Corporation', Sector: 'Energy', Symbol: 'HES' },
  {
    Name: 'Hewlett Packard Enterprise',
    Sector: 'Technology',
    Symbol: 'HPE',
  },
  {
    Name: 'Hilton Worldwide Holdings Inc',
    Sector: 'Consumer',
    Symbol: 'HLT',
  },
  { Name: 'Hologic', Sector: 'Health Care', Symbol: 'HOLX' },
  { Name: 'Home Depot', Sector: 'Consumer', Symbol: 'HD' },
  { Name: "Honeywell Int'l Inc.", Sector: 'Industrials', Symbol: 'HON' },
  { Name: 'Hormel Foods Corp.', Sector: 'Consumer', Symbol: 'HRL' },
  { Name: 'Host Hotels & Resorts', Sector: 'Real Estate', Symbol: 'HST' },
  { Name: 'HP Inc.', Sector: 'Technology', Symbol: 'HPQ' },
  { Name: 'Humana Inc.', Sector: 'Health Care', Symbol: 'HUM' },
  { Name: 'Huntington Bancshares', Sector: 'Financials', Symbol: 'HBAN' },
  {
    Name: 'Huntington Ingalls Industries',
    Sector: 'Industrials',
    Symbol: 'HII',
  },
  { Name: 'IDEXX Laboratories', Sector: 'Health Care', Symbol: 'IDXX' },
  { Name: 'IHS Markit Ltd.', Sector: 'Industrials', Symbol: 'INFO' },
  { Name: 'Illinois Tool Works', Sector: 'Industrials', Symbol: 'ITW' },
  { Name: 'Illumina Inc', Sector: 'Health Care', Symbol: 'ILMN' },
  { Name: 'Incyte', Sector: 'Health Care', Symbol: 'INCY' },
  { Name: 'Ingersoll-Rand PLC', Sector: 'Industrials', Symbol: 'IR' },
  { Name: 'Intel Corp.', Sector: 'Technology', Symbol: 'INTC' },
  { Name: 'Intercontinental Exchange', Sector: 'Financials', Symbol: 'ICE' },
  {
    Name: 'International Business Machines',
    Sector: 'Technology',
    Symbol: 'IBM',
  },
  { Name: 'International Paper', Sector: 'Industrials', Symbol: 'IP' },
  {
    Name: 'Interpublic Group',
    Sector: 'Consumer',
    Symbol: 'IPG',
  },
  { Name: 'Intl Flavors & Fragrances', Sector: 'Industrials', Symbol: 'IFF' },
  { Name: 'Intuit Inc.', Sector: 'Technology', Symbol: 'INTU' },
  { Name: 'Intuitive Surgical Inc.', Sector: 'Health Care', Symbol: 'ISRG' },
  { Name: 'Invesco Ltd.', Sector: 'Financials', Symbol: 'IVZ' },
  {
    Name: 'IPG Photonics Corp.',
    Sector: 'Technology',
    Symbol: 'IPGP',
  },
  { Name: 'IQVIA Holdings Inc.', Sector: 'Health Care', Symbol: 'IQV' },
  { Name: 'Iron Mountain Incorporated', Sector: 'Real Estate', Symbol: 'IRM' },
  {
    Name: 'J. B. Hunt Transport Services',
    Sector: 'Industrials',
    Symbol: 'JBHT',
  },
  { Name: 'Jacobs Engineering Group', Sector: 'Industrials', Symbol: 'JEC' },
  { Name: 'JM Smucker', Sector: 'Consumer', Symbol: 'SJM' },
  { Name: 'Johnson & Johnson', Sector: 'Health Care', Symbol: 'JNJ' },
  {
    Name: 'Johnson Controls International',
    Sector: 'Industrials',
    Symbol: 'JCI',
  },
  { Name: 'JPMorgan Chase & Co.', Sector: 'Financials', Symbol: 'JPM' },
  {
    Name: 'Juniper Networks',
    Sector: 'Technology',
    Symbol: 'JNPR',
  },
  { Name: 'Kansas City Southern', Sector: 'Industrials', Symbol: 'KSU' },
  { Name: 'Kellogg Co.', Sector: 'Consumer', Symbol: 'K' },
  { Name: 'KeyCorp', Sector: 'Financials', Symbol: 'KEY' },
  { Name: 'Kimberly-Clark', Sector: 'Consumer', Symbol: 'KMB' },
  { Name: 'Kimco Realty', Sector: 'Real Estate', Symbol: 'KIM' },
  { Name: 'Kinder Morgan', Sector: 'Energy', Symbol: 'KMI' },
  {
    Name: 'KLA-Tencor Corp.',
    Sector: 'Technology',
    Symbol: 'KLAC',
  },
  { Name: "Kohl's Corp.", Sector: 'Consumer', Symbol: 'KSS' },
  { Name: 'Kraft Heinz Co', Sector: 'Consumer', Symbol: 'KHC' },
  { Name: 'Kroger Co.', Sector: 'Consumer', Symbol: 'KR' },
  { Name: 'L Brands Inc.', Sector: 'Consumer', Symbol: 'LB' },
  { Name: 'L-3 Communications Holdings', Sector: 'Industrials', Symbol: 'LLL' },
  {
    Name: 'Laboratory Corp. of America Holding',
    Sector: 'Health Care',
    Symbol: 'LH',
  },
  { Name: 'Lam Research', Sector: 'Technology', Symbol: 'LRCX' },
  { Name: 'Leggett & Platt', Sector: 'Consumer', Symbol: 'LEG' },
  { Name: 'Lennar Corp.', Sector: 'Consumer', Symbol: 'LEN' },
  { Name: 'Leucadia National Corp.', Sector: 'Financials', Symbol: 'LUK' },
  { Name: 'Lilly (Eli) & Co.', Sector: 'Health Care', Symbol: 'LLY' },
  { Name: 'Lincoln National', Sector: 'Financials', Symbol: 'LNC' },
  { Name: 'LKQ Corporation', Sector: 'Consumer', Symbol: 'LKQ' },
  { Name: 'Lockheed Martin Corp.', Sector: 'Industrials', Symbol: 'LMT' },
  { Name: 'Loews Corp.', Sector: 'Financials', Symbol: 'L' },
  { Name: "Lowe's Cos.", Sector: 'Consumer', Symbol: 'LOW' },
  { Name: 'LyondellBasell', Sector: 'Industrials', Symbol: 'LYB' },
  { Name: 'M&T Bank Corp.', Sector: 'Financials', Symbol: 'MTB' },
  { Name: 'Macerich', Sector: 'Real Estate', Symbol: 'MAC' },
  { Name: "Macy's Inc.", Sector: 'Consumer', Symbol: 'M' },
  { Name: 'Marathon Oil Corp.', Sector: 'Energy', Symbol: 'MRO' },
  { Name: 'Marathon Petroleum', Sector: 'Energy', Symbol: 'MPC' },
  { Name: "Marriott Int'l.", Sector: 'Consumer', Symbol: 'MAR' },
  { Name: 'Marsh & McLennan', Sector: 'Financials', Symbol: 'MMC' },
  { Name: 'Martin Marietta Industrials', Sector: 'Industrials', Symbol: 'MLM' },
  { Name: 'Masco Corp.', Sector: 'Industrials', Symbol: 'MAS' },
  { Name: 'Mastercard Inc.', Sector: 'Technology', Symbol: 'MA' },
  { Name: 'Mattel Inc.', Sector: 'Consumer', Symbol: 'MAT' },
  { Name: 'McCormick & Co.', Sector: 'Consumer', Symbol: 'MKC' },
  { Name: "McDonald's Corp.", Sector: 'Consumer', Symbol: 'MCD' },
  { Name: 'McKesson Corp.', Sector: 'Health Care', Symbol: 'MCK' },
  { Name: 'Medtronic plc', Sector: 'Health Care', Symbol: 'MDT' },
  { Name: 'Merck & Co.', Sector: 'Health Care', Symbol: 'MRK' },
  { Name: 'Meta Platforms', Sector: 'Technology', Symbol: 'META' },
  { Name: 'MetLife Inc.', Sector: 'Financials', Symbol: 'MET' },
  { Name: 'Mettler Toledo', Sector: 'Health Care', Symbol: 'MTD' },
  {
    Name: 'MGM Resorts International',
    Sector: 'Consumer',
    Symbol: 'MGM',
  },
  {
    Name: 'Michael Kors Holdings',
    Sector: 'Consumer',
    Symbol: 'KORS',
  },
  {
    Name: 'Microchip Technology',
    Sector: 'Technology',
    Symbol: 'MCHP',
  },
  { Name: 'Micron Technology', Sector: 'Technology', Symbol: 'MU' },
  { Name: 'Microsoft Corp.', Sector: 'Technology', Symbol: 'MSFT' },
  { Name: 'Mid-America Apartments', Sector: 'Real Estate', Symbol: 'MAA' },
  {
    Name: 'Mohawk Industries',
    Sector: 'Consumer',
    Symbol: 'MHK',
  },
  {
    Name: 'Molson Coors Brewing Company',
    Sector: 'Consumer',
    Symbol: 'TAP',
  },
  {
    Name: 'Mondelez International',
    Sector: 'Consumer',
    Symbol: 'MDLZ',
  },
  { Name: 'Monsanto Co.', Sector: 'Industrials', Symbol: 'MON' },
  { Name: 'Monster Beverage', Sector: 'Consumer', Symbol: 'MNST' },
  { Name: "Moody's Corp", Sector: 'Financials', Symbol: 'MCO' },
  { Name: 'Morgan Stanley', Sector: 'Financials', Symbol: 'MS' },
  {
    Name: 'Motorola Solutions Inc.',
    Sector: 'Technology',
    Symbol: 'MSI',
  },
  { Name: 'Mylan N.V.', Sector: 'Health Care', Symbol: 'MYL' },
  { Name: 'Nasdaq, Inc.', Sector: 'Financials', Symbol: 'NDAQ' },
  { Name: 'National Oilwell Varco Inc.', Sector: 'Energy', Symbol: 'NOV' },
  { Name: 'Navient', Sector: 'Financials', Symbol: 'NAVI' },
  { Name: 'Nektar Therapeutics', Sector: 'Health Care', Symbol: 'NKTR' },
  { Name: 'NetApp', Sector: 'Technology', Symbol: 'NTAP' },
  { Name: 'Netflix Inc.', Sector: 'Technology', Symbol: 'NFLX' },
  { Name: 'Newell Brands', Sector: 'Consumer', Symbol: 'NWL' },
  { Name: 'Newfield Exploration Co', Sector: 'Energy', Symbol: 'NFX' },
  { Name: 'Newmont Mining Corporation', Sector: 'Industrials', Symbol: 'NEM' },
  {
    Name: 'News Corp. Class A',
    Sector: 'Consumer',
    Symbol: 'NWSA',
  },
  {
    Name: 'News Corp. Class B',
    Sector: 'Consumer',
    Symbol: 'NWS',
  },
  { Name: 'NextEra Energy', Sector: 'Utilities', Symbol: 'NEE' },
  { Name: 'Nielsen Holdings', Sector: 'Industrials', Symbol: 'NLSN' },
  { Name: 'Nike', Sector: 'Consumer', Symbol: 'NKE' },
  { Name: 'NiSource Inc.', Sector: 'Utilities', Symbol: 'NI' },
  { Name: 'Noble Energy Inc', Sector: 'Energy', Symbol: 'NBL' },
  { Name: 'Nordstrom', Sector: 'Consumer', Symbol: 'JWN' },
  { Name: 'Norfolk Southern Corp.', Sector: 'Industrials', Symbol: 'NSC' },
  { Name: 'Northern Trust Corp.', Sector: 'Financials', Symbol: 'NTRS' },
  { Name: 'Northrop Grumman Corp.', Sector: 'Industrials', Symbol: 'NOC' },
  {
    Name: 'Norwegian Cruise Line',
    Sector: 'Consumer',
    Symbol: 'NCLH',
  },
  { Name: 'NRG Energy', Sector: 'Utilities', Symbol: 'NRG' },
  { Name: 'Nucor Corp.', Sector: 'Industrials', Symbol: 'NUE' },
  {
    Name: 'Nvidia Corporation',
    Sector: 'Technology',
    Symbol: 'NVDA',
  },
  {
    Name: "O'Reilly Automotive",
    Sector: 'Consumer',
    Symbol: 'ORLY',
  },
  { Name: 'Occidental Petroleum', Sector: 'Energy', Symbol: 'OXY' },
  { Name: 'Omnicom Group', Sector: 'Consumer', Symbol: 'OMC' },
  { Name: 'ONEOK', Sector: 'Energy', Symbol: 'OKE' },
  { Name: 'Oracle Corp.', Sector: 'Technology', Symbol: 'ORCL' },
  { Name: 'PACCAR Inc.', Sector: 'Industrials', Symbol: 'PCAR' },
  {
    Name: 'Packaging Corporation of America',
    Sector: 'Industrials',
    Symbol: 'PKG',
  },
  { Name: 'Parker-Hannifin', Sector: 'Industrials', Symbol: 'PH' },
  { Name: 'Paychex Inc.', Sector: 'Technology', Symbol: 'PAYX' },
  { Name: 'PayPal', Sector: 'Technology', Symbol: 'PYPL' },
  { Name: 'Pentair Ltd.', Sector: 'Industrials', Symbol: 'PNR' },
  { Name: "People's United Financial", Sector: 'Financials', Symbol: 'PBCT' },
  { Name: 'PepsiCo Inc.', Sector: 'Consumer', Symbol: 'PEP' },
  { Name: 'PerkinElmer', Sector: 'Health Care', Symbol: 'PKI' },
  { Name: 'Perrigo', Sector: 'Health Care', Symbol: 'PRGO' },
  { Name: 'Pfizer Inc.', Sector: 'Health Care', Symbol: 'PFE' },
  { Name: 'PG&E Corp.', Sector: 'Utilities', Symbol: 'PCG' },
  {
    Name: 'Philip Morris International',
    Sector: 'Consumer',
    Symbol: 'PM',
  },
  { Name: 'Phillips 66', Sector: 'Energy', Symbol: 'PSX' },
  { Name: 'Pinnacle West Capital', Sector: 'Utilities', Symbol: 'PNW' },
  { Name: 'Pioneer Natural Resources', Sector: 'Energy', Symbol: 'PXD' },
  { Name: 'PNC Financial Services', Sector: 'Financials', Symbol: 'PNC' },
  {
    Name: 'Polo Ralph Lauren Corp.',
    Sector: 'Consumer',
    Symbol: 'RL',
  },
  { Name: 'PPG Industries', Sector: 'Industrials', Symbol: 'PPG' },
  { Name: 'PPL Corp.', Sector: 'Utilities', Symbol: 'PPL' },
  { Name: 'Praxair Inc.', Sector: 'Industrials', Symbol: 'PX' },
  { Name: 'Principal Financial Group', Sector: 'Financials', Symbol: 'PFG' },
  { Name: 'Procter & Gamble', Sector: 'Consumer', Symbol: 'PG' },
  { Name: 'Progressive Corp.', Sector: 'Financials', Symbol: 'PGR' },
  { Name: 'Prologis', Sector: 'Real Estate', Symbol: 'PLD' },
  { Name: 'Prudential Financial', Sector: 'Financials', Symbol: 'PRU' },
  { Name: 'Public Serv. Enterprise Inc.', Sector: 'Utilities', Symbol: 'PEG' },
  { Name: 'Public Storage', Sector: 'Real Estate', Symbol: 'PSA' },
  { Name: 'Pulte Homes Inc.', Sector: 'Consumer', Symbol: 'PHM' },
  { Name: 'PVH Corp.', Sector: 'Consumer', Symbol: 'PVH' },
  { Name: 'Qorvo', Sector: 'Technology', Symbol: 'QRVO' },
  { Name: 'QUALCOMM Inc.', Sector: 'Technology', Symbol: 'QCOM' },
  { Name: 'Quanta Services Inc.', Sector: 'Industrials', Symbol: 'PWR' },
  { Name: 'Quest Diagnostics', Sector: 'Health Care', Symbol: 'DGX' },
  { Name: 'Range Resources Corp.', Sector: 'Energy', Symbol: 'RRC' },
  { Name: 'Raymond James Financial Inc.', Sector: 'Financials', Symbol: 'RJF' },
  { Name: 'Raytheon Co.', Sector: 'Industrials', Symbol: 'RTN' },
  { Name: 'Realty Income Corporation', Sector: 'Real Estate', Symbol: 'O' },
  { Name: 'Red Hat Inc.', Sector: 'Technology', Symbol: 'RHT' },
  { Name: 'Regency Centers Corporation', Sector: 'Real Estate', Symbol: 'REG' },
  { Name: 'Regeneron', Sector: 'Health Care', Symbol: 'REGN' },
  { Name: 'Regions Financial Corp.', Sector: 'Financials', Symbol: 'RF' },
  { Name: 'Republic Services Inc', Sector: 'Industrials', Symbol: 'RSG' },
  { Name: 'ResMed', Sector: 'Health Care', Symbol: 'RMD' },
  { Name: 'Robert Half International', Sector: 'Industrials', Symbol: 'RHI' },
  { Name: 'Rockwell Automation Inc.', Sector: 'Industrials', Symbol: 'ROK' },
  { Name: 'Rockwell Collins', Sector: 'Industrials', Symbol: 'COL' },
  { Name: 'Roper Technologies', Sector: 'Industrials', Symbol: 'ROP' },
  { Name: 'Ross Stores', Sector: 'Consumer', Symbol: 'ROST' },
  {
    Name: 'Royal Caribbean Cruises Ltd',
    Sector: 'Consumer',
    Symbol: 'RCL',
  },
  { Name: 'S&P Global, Inc.', Sector: 'Financials', Symbol: 'SPGI' },
  { Name: 'Salesforce.com', Sector: 'Technology', Symbol: 'CRM' },
  { Name: 'SBA Communications', Sector: 'Real Estate', Symbol: 'SBAC' },
  { Name: 'SCANA Corp', Sector: 'Utilities', Symbol: 'SCG' },
  { Name: 'Schlumberger Ltd.', Sector: 'Energy', Symbol: 'SLB' },
  {
    Name: 'Seagate Technology',
    Sector: 'Technology',
    Symbol: 'STX',
  },
  { Name: 'Sealed Air', Sector: 'Industrials', Symbol: 'SEE' },
  { Name: 'Sempra Energy', Sector: 'Utilities', Symbol: 'SRE' },
  { Name: 'Sherwin-Williams', Sector: 'Industrials', Symbol: 'SHW' },
  { Name: 'Simon Property Group Inc', Sector: 'Real Estate', Symbol: 'SPG' },
  {
    Name: 'Skyworks Solutions',
    Sector: 'Technology',
    Symbol: 'SWKS',
  },
  { Name: 'SL Green Realty', Sector: 'Real Estate', Symbol: 'SLG' },
  { Name: 'Snap-On Inc.', Sector: 'Consumer', Symbol: 'SNA' },
  { Name: 'Southern Co.', Sector: 'Utilities', Symbol: 'SO' },
  { Name: 'Southwest Airlines', Sector: 'Industrials', Symbol: 'LUV' },
  {
    Name: 'Stanley Black & Decker',
    Sector: 'Consumer',
    Symbol: 'SWK',
  },
  { Name: 'Starbucks Corp.', Sector: 'Consumer', Symbol: 'SBUX' },
  { Name: 'State Street Corp.', Sector: 'Financials', Symbol: 'STT' },
  { Name: 'Stericycle Inc', Sector: 'Industrials', Symbol: 'SRCL' },
  { Name: 'Stryker Corp.', Sector: 'Health Care', Symbol: 'SYK' },
  { Name: 'SunTrust Banks', Sector: 'Financials', Symbol: 'STI' },
  { Name: 'SVB Financial', Sector: 'Financials', Symbol: 'SIVB' },
  { Name: 'Symantec Corp.', Sector: 'Technology', Symbol: 'SYMC' },
  { Name: 'Synchrony Financial', Sector: 'Financials', Symbol: 'SYF' },
  { Name: 'Synopsys Inc.', Sector: 'Technology', Symbol: 'SNPS' },
  { Name: 'Sysco Corp.', Sector: 'Consumer', Symbol: 'SYY' },
  { Name: 'T. Rowe Price Group', Sector: 'Financials', Symbol: 'TROW' },
  {
    Name: 'Take-Two Interactive',
    Sector: 'Technology',
    Symbol: 'TTWO',
  },
  { Name: 'Tapestry, Inc.', Sector: 'Consumer', Symbol: 'TPR' },
  { Name: 'Target Corp.', Sector: 'Consumer', Symbol: 'TGT' },
  {
    Name: 'TE Connectivity Ltd.',
    Sector: 'Technology',
    Symbol: 'TEL',
  },
  { Name: 'TechnipFMC', Sector: 'Energy', Symbol: 'FTI' },
  {
    Name: 'Texas Instruments',
    Sector: 'Technology',
    Symbol: 'TXN',
  },
  { Name: 'Textron Inc.', Sector: 'Industrials', Symbol: 'TXT' },
  {
    Name: 'The Bank of New York Mellon Corp.',
    Sector: 'Financials',
    Symbol: 'BK',
  },
  { Name: 'The Clorox Company', Sector: 'Consumer', Symbol: 'CLX' },
  { Name: 'The Cooper Companies', Sector: 'Health Care', Symbol: 'COO' },
  { Name: 'The Hershey Company', Sector: 'Consumer', Symbol: 'HSY' },
  { Name: 'The Mosaic Company', Sector: 'Industrials', Symbol: 'MOS' },
  { Name: 'The Travelers Companies Inc.', Sector: 'Financials', Symbol: 'TRV' },
  {
    Name: 'The Walt Disney Company',
    Sector: 'Consumer',
    Symbol: 'DIS',
  },
  { Name: 'Thermo Fisher Scientific', Sector: 'Health Care', Symbol: 'TMO' },
  { Name: 'Tiffany & Co.', Sector: 'Consumer', Symbol: 'TIF' },
  { Name: 'Time Warner Inc.', Sector: 'Consumer', Symbol: 'TWX' },
  {
    Name: 'TJX Companies Inc.',
    Sector: 'Consumer',
    Symbol: 'TJX',
  },
  { Name: 'Torchmark Corp.', Sector: 'Financials', Symbol: 'TMK' },
  {
    Name: 'Total System Services',
    Sector: 'Technology',
    Symbol: 'TSS',
  },
  {
    Name: 'Tractor Supply Company',
    Sector: 'Consumer',
    Symbol: 'TSCO',
  },
  { Name: 'TransDigm Group', Sector: 'Industrials', Symbol: 'TDG' },
  { Name: 'TripAdvisor', Sector: 'Consumer', Symbol: 'TRIP' },
  {
    Name: 'Twenty-First Century Fox Class A',
    Sector: 'Consumer',
    Symbol: 'FOXA',
  },
  {
    Name: 'Twenty-First Century Fox Class B',
    Sector: 'Consumer',
    Symbol: 'FOX',
  },
  { Name: 'Tyson Foods', Sector: 'Consumer', Symbol: 'TSN' },
  { Name: 'U.S. Bancorp', Sector: 'Financials', Symbol: 'USB' },
  { Name: 'UDR Inc', Sector: 'Real Estate', Symbol: 'UDR' },
  { Name: 'Ulta Beauty', Sector: 'Consumer', Symbol: 'ULTA' },
  {
    Name: 'Under Armour Class A',
    Sector: 'Consumer',
    Symbol: 'UAA',
  },
  {
    Name: 'Under Armour Class C',
    Sector: 'Consumer',
    Symbol: 'UA',
  },
  { Name: 'Union Pacific', Sector: 'Industrials', Symbol: 'UNP' },
  { Name: 'United Continental Holdings', Sector: 'Industrials', Symbol: 'UAL' },
  { Name: 'United Health Group Inc.', Sector: 'Health Care', Symbol: 'UNH' },
  { Name: 'United Parcel Service', Sector: 'Industrials', Symbol: 'UPS' },
  { Name: 'United Rentals, Inc.', Sector: 'Industrials', Symbol: 'URI' },
  { Name: 'United Technologies', Sector: 'Industrials', Symbol: 'UTX' },
  {
    Name: 'Universal Health Services, Inc.',
    Sector: 'Health Care',
    Symbol: 'UHS',
  },
  { Name: 'Unum Group', Sector: 'Financials', Symbol: 'UNM' },
  { Name: 'V.F. Corp.', Sector: 'Consumer', Symbol: 'VFC' },
  { Name: 'Valero Energy', Sector: 'Energy', Symbol: 'VLO' },
  { Name: 'Varian Medical Systems', Sector: 'Health Care', Symbol: 'VAR' },
  { Name: 'Ventas Inc', Sector: 'Real Estate', Symbol: 'VTR' },
  { Name: 'Verisign Inc.', Sector: 'Technology', Symbol: 'VRSN' },
  { Name: 'Verisk Analytics', Sector: 'Industrials', Symbol: 'VRSK' },
  {
    Name: 'Verizon Communications',
    Sector: 'Technology',
    Symbol: 'VZ',
  },
  { Name: 'Vertex Pharmaceuticals Inc', Sector: 'Health Care', Symbol: 'VRTX' },
  { Name: 'Viacom Inc.', Sector: 'Consumer', Symbol: 'VIAB' },
  { Name: 'Visa Inc.', Sector: 'Technology', Symbol: 'V' },
  { Name: 'Vornado Realty Trust', Sector: 'Real Estate', Symbol: 'VNO' },
  { Name: 'Vulcan Industrials', Sector: 'Industrials', Symbol: 'VMC' },
  { Name: 'Wal-Mart Stores', Sector: 'Consumer', Symbol: 'WMT' },
  {
    Name: 'Walgreens Boots Alliance',
    Sector: 'Consumer',
    Symbol: 'WBA',
  },
  { Name: 'Waste Management Inc.', Sector: 'Industrials', Symbol: 'WM' },
  { Name: 'Waters Corporation', Sector: 'Health Care', Symbol: 'WAT' },
  { Name: 'Wec Energy Group Inc', Sector: 'Utilities', Symbol: 'WEC' },
  { Name: 'Wells Fargo', Sector: 'Financials', Symbol: 'WFC' },
  { Name: 'Welltower Inc.', Sector: 'Real Estate', Symbol: 'WELL' },
  { Name: 'Western Digital', Sector: 'Technology', Symbol: 'WDC' },
  { Name: 'Western Union Co', Sector: 'Technology', Symbol: 'WU' },
  { Name: 'WestRock Company', Sector: 'Industrials', Symbol: 'WRK' },
  { Name: 'Weyerhaeuser Corp.', Sector: 'Real Estate', Symbol: 'WY' },
  { Name: 'Whirlpool Corp.', Sector: 'Consumer', Symbol: 'WHR' },
  { Name: 'Williams Cos.', Sector: 'Energy', Symbol: 'WMB' },
  { Name: 'Willis Towers Watson', Sector: 'Financials', Symbol: 'WLTW' },
  {
    Name: 'Wyndham Worldwide',
    Sector: 'Consumer',
    Symbol: 'WYN',
  },
  {
    Name: 'Wynn Resorts Ltd',
    Sector: 'Consumer',
    Symbol: 'WYNN',
  },
  { Name: 'Xcel Energy Inc', Sector: 'Utilities', Symbol: 'XEL' },
  { Name: 'Xerox Corp.', Sector: 'Technology', Symbol: 'XRX' },
  { Name: 'Xilinx Inc', Sector: 'Technology', Symbol: 'XLNX' },
  { Name: 'XL Capital', Sector: 'Financials', Symbol: 'XL' },
  { Name: 'Xylem Inc.', Sector: 'Industrials', Symbol: 'XYL' },
  { Name: 'Yum! Brands Inc', Sector: 'Consumer', Symbol: 'YUM' },
  { Name: 'Zimmer Biomet Holdings', Sector: 'Health Care', Symbol: 'ZBH' },
  { Name: 'Zions Bancorp', Sector: 'Financials', Symbol: 'ZION' },
  { Name: 'Zoetis', Sector: 'Health Care', Symbol: 'ZTS' },
];
